# Generated by Django 4.2.1 on 2023-05-15 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='identifiers',
            new_name='identifier',
        ),
        migrations.AlterField(
            model_name='plant',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant_information', to='website.plantinformation'),
        ),
    ]
