# Generated by Django 4.2.1 on 2023-05-15 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_identifiers_plant_identifier_alter_plant_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Identifier',
            new_name='PlantIdentifier',
        ),
    ]
