# Generated by Django 4.2.1 on 2023-05-15 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_identifier_plantidentifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2023, 5, 15, 4, 2, 22, 741961, tzinfo=datetime.timezone.utc)),
        ),
    ]
