# Generated by Django 4.2.1 on 2023-05-15 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_plant_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
