# Generated by Django 4.2.1 on 2023-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_plant_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinformation',
            name='height_max',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='plantinformation',
            name='height_min',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
