# Generated by Django 4.2.1 on 2023-05-16 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_plant_identifier_alter_plant_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='identifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='website.plantidentifier'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='website.plantinformation'),
        ),
    ]
