# Generated by Django 4.2.1 on 2023-05-16 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_plant_identifier_alter_plant_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2023, 5, 16, 19, 23, 1, 734556, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plantinformation',
            name='bloom_end',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December'), ('Nil', 'Not Set')], default='Nil', max_length=8),
        ),
        migrations.AlterField(
            model_name='plantinformation',
            name='bloom_start',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December'), ('Nil', 'Not Set')], default='Nil', max_length=8),
        ),
        migrations.AlterField(
            model_name='plantinformation',
            name='height_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='plantinformation',
            name='height_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
