# Generated by Django 4.2.1 on 2023-05-16 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_plant_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='date_added',
        ),
        migrations.AddField(
            model_name='plant',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 20, 15, 51, 354031, tzinfo=datetime.timezone.utc)),
        ),
    ]
