# Generated by Django 4.2.1 on 2023-05-16 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_plant_date_added_plant_time_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='time_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
