# Generated by Django 4.2.1 on 2023-05-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_plant_time_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='time_added',
            new_name='datetime_added',
        ),
    ]
