# Generated by Django 4.2.1 on 2023-05-22 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=128)),
                ('common_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PlantInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloom_start', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December'), ('Nil', 'Not Set')], default='Nil', max_length=8)),
                ('bloom_end', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December'), ('Nil', 'Not Set')], default='Nil', max_length=8)),
                ('height_min', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('height_max', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10240)),
                ('datetime_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('identifier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='backend.plantidentifier')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='backend.plantinformation')),
            ],
        ),
    ]
