# Generated by Django 4.2.2 on 2023-06-19 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_editplantrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editplantrecord',
            name='edited_plant',
        ),
        migrations.RemoveField(
            model_name='editplantrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='datetime_added',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='identifier',
        ),
        migrations.AddField(
            model_name='editplantrecord',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='plant_edits', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editplantrecord',
            name='current_plant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='backend.plant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editplantrecord',
            name='edits',
            field=models.JSONField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editplantrecord',
            name='submission_status',
            field=models.CharField(choices=[('NIL', 'Not Submitted'), ('APP', 'Approved'), ('REJ', 'Rejected'), ('PEN', 'Pending')], default='NIL', max_length=3),
        ),
        migrations.AddField(
            model_name='plant',
            name='common_name',
            field=models.CharField(default='Common Name Not Set', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='latin_name',
            field=models.CharField(default='Latin Name Not Set', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='editplantrecord',
            name='comments',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.DeleteModel(
            name='PlantIdentifier',
        ),
    ]
