/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountResponse
 */
export interface AccountResponse {
    /**
     * 
     * @type {number}
     * @memberof AccountResponse
     */
    readonly id: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof AccountResponse
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    email?: string;
}

/**
 * Check if a given object implements the AccountResponse interface.
 */
export function instanceOfAccountResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function AccountResponseFromJSON(json: any): AccountResponse {
    return AccountResponseFromJSONTyped(json, false);
}

export function AccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function AccountResponseToJSON(value?: AccountResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'email': value.email,
    };
}

