/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `Jan` - January
* `Feb` - February
* `Mar` - March
* `Apr` - April
* `May` - May
* `Jun` - June
* `Jul` - July
* `Aug` - August
* `Sep` - September
* `Oct` - October
* `Nov` - November
* `Dec` - December
* `Nil` - Not Set
 * @export
 */
export const BloomStartEnum = {
    Jan: 'Jan',
    Feb: 'Feb',
    Mar: 'Mar',
    Apr: 'Apr',
    May: 'May',
    Jun: 'Jun',
    Jul: 'Jul',
    Aug: 'Aug',
    Sep: 'Sep',
    Oct: 'Oct',
    Nov: 'Nov',
    Dec: 'Dec',
    Nil: 'Nil'
} as const;
export type BloomStartEnum = typeof BloomStartEnum[keyof typeof BloomStartEnum];


export function BloomStartEnumFromJSON(json: any): BloomStartEnum {
    return BloomStartEnumFromJSONTyped(json, false);
}

export function BloomStartEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BloomStartEnum {
    return json as BloomStartEnum;
}

export function BloomStartEnumToJSON(value?: BloomStartEnum | null): any {
    return value as any;
}

