/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PlantInformation } from './PlantInformation';
import {
    PlantInformationFromJSON,
    PlantInformationFromJSONTyped,
    PlantInformationToJSON,
} from './PlantInformation';

/**
 * 
 * @export
 * @interface PaginatedPlantInformationList
 */
export interface PaginatedPlantInformationList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPlantInformationList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPlantInformationList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPlantInformationList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PlantInformation>}
     * @memberof PaginatedPlantInformationList
     */
    results?: Array<PlantInformation>;
}

/**
 * Check if a given object implements the PaginatedPlantInformationList interface.
 */
export function instanceOfPaginatedPlantInformationList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedPlantInformationListFromJSON(json: any): PaginatedPlantInformationList {
    return PaginatedPlantInformationListFromJSONTyped(json, false);
}

export function PaginatedPlantInformationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPlantInformationList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(PlantInformationFromJSON)),
    };
}

export function PaginatedPlantInformationListToJSON(value?: PaginatedPlantInformationList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(PlantInformationToJSON)),
    };
}

