/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PlantIdentifier } from './PlantIdentifier';
import {
    PlantIdentifierFromJSON,
    PlantIdentifierFromJSONTyped,
    PlantIdentifierToJSON,
} from './PlantIdentifier';

/**
 * 
 * @export
 * @interface PaginatedPlantIdentifierList
 */
export interface PaginatedPlantIdentifierList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPlantIdentifierList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPlantIdentifierList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPlantIdentifierList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PlantIdentifier>}
     * @memberof PaginatedPlantIdentifierList
     */
    results?: Array<PlantIdentifier>;
}

/**
 * Check if a given object implements the PaginatedPlantIdentifierList interface.
 */
export function instanceOfPaginatedPlantIdentifierList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedPlantIdentifierListFromJSON(json: any): PaginatedPlantIdentifierList {
    return PaginatedPlantIdentifierListFromJSONTyped(json, false);
}

export function PaginatedPlantIdentifierListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPlantIdentifierList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(PlantIdentifierFromJSON)),
    };
}

export function PaginatedPlantIdentifierListToJSON(value?: PaginatedPlantIdentifierList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(PlantIdentifierToJSON)),
    };
}

