/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Plant } from './Plant';
import {
    PlantFromJSON,
    PlantFromJSONTyped,
    PlantToJSON,
} from './Plant';

/**
 * 
 * @export
 * @interface PaginatedPlantList
 */
export interface PaginatedPlantList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPlantList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPlantList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPlantList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Plant>}
     * @memberof PaginatedPlantList
     */
    results?: Array<Plant>;
}

/**
 * Check if a given object implements the PaginatedPlantList interface.
 */
export function instanceOfPaginatedPlantList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedPlantListFromJSON(json: any): PaginatedPlantList {
    return PaginatedPlantListFromJSONTyped(json, false);
}

export function PaginatedPlantListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPlantList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(PlantFromJSON)),
    };
}

export function PaginatedPlantListToJSON(value?: PaginatedPlantList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(PlantToJSON)),
    };
}

