/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BloomEndEnum } from './BloomEndEnum';
import {
    BloomEndEnumFromJSON,
    BloomEndEnumFromJSONTyped,
    BloomEndEnumToJSON,
} from './BloomEndEnum';
import type { BloomStartEnum } from './BloomStartEnum';
import {
    BloomStartEnumFromJSON,
    BloomStartEnumFromJSONTyped,
    BloomStartEnumToJSON,
} from './BloomStartEnum';

/**
 * 
 * @export
 * @interface PatchedPlantInformation
 */
export interface PatchedPlantInformation {
    /**
     * 
     * @type {number}
     * @memberof PatchedPlantInformation
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedPlantInformation
     */
    readonly plant?: number;
    /**
     * 
     * @type {BloomStartEnum}
     * @memberof PatchedPlantInformation
     */
    bloom_start?: BloomStartEnum;
    /**
     * 
     * @type {BloomEndEnum}
     * @memberof PatchedPlantInformation
     */
    bloom_end?: BloomEndEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedPlantInformation
     */
    height_min?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedPlantInformation
     */
    height_max?: string;
}

/**
 * Check if a given object implements the PatchedPlantInformation interface.
 */
export function instanceOfPatchedPlantInformation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedPlantInformationFromJSON(json: any): PatchedPlantInformation {
    return PatchedPlantInformationFromJSONTyped(json, false);
}

export function PatchedPlantInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedPlantInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'plant': !exists(json, 'plant') ? undefined : json['plant'],
        'bloom_start': !exists(json, 'bloom_start') ? undefined : BloomStartEnumFromJSON(json['bloom_start']),
        'bloom_end': !exists(json, 'bloom_end') ? undefined : BloomEndEnumFromJSON(json['bloom_end']),
        'height_min': !exists(json, 'height_min') ? undefined : json['height_min'],
        'height_max': !exists(json, 'height_max') ? undefined : json['height_max'],
    };
}

export function PatchedPlantInformationToJSON(value?: PatchedPlantInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bloom_start': BloomStartEnumToJSON(value.bloom_start),
        'bloom_end': BloomEndEnumToJSON(value.bloom_end),
        'height_min': value.height_min,
        'height_max': value.height_max,
    };
}

