/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedPlantIdentifier
 */
export interface PatchedPlantIdentifier {
    /**
     * 
     * @type {number}
     * @memberof PatchedPlantIdentifier
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedPlantIdentifier
     */
    readonly plant?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedPlantIdentifier
     */
    latin_name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedPlantIdentifier
     */
    common_name?: string;
}

/**
 * Check if a given object implements the PatchedPlantIdentifier interface.
 */
export function instanceOfPatchedPlantIdentifier(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedPlantIdentifierFromJSON(json: any): PatchedPlantIdentifier {
    return PatchedPlantIdentifierFromJSONTyped(json, false);
}

export function PatchedPlantIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedPlantIdentifier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'plant': !exists(json, 'plant') ? undefined : json['plant'],
        'latin_name': !exists(json, 'latin_name') ? undefined : json['latin_name'],
        'common_name': !exists(json, 'common_name') ? undefined : json['common_name'],
    };
}

export function PatchedPlantIdentifierToJSON(value?: PatchedPlantIdentifier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'latin_name': value.latin_name,
        'common_name': value.common_name,
    };
}

