/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PlantIdentifier } from './PlantIdentifier';
import {
    PlantIdentifierFromJSON,
    PlantIdentifierFromJSONTyped,
    PlantIdentifierToJSON,
} from './PlantIdentifier';
import type { PlantInformation } from './PlantInformation';
import {
    PlantInformationFromJSON,
    PlantInformationFromJSONTyped,
    PlantInformationToJSON,
} from './PlantInformation';

/**
 * 
 * @export
 * @interface PatchedPlant
 */
export interface PatchedPlant {
    /**
     * 
     * @type {number}
     * @memberof PatchedPlant
     */
    readonly id?: number;
    /**
     * 
     * @type {PlantIdentifier}
     * @memberof PatchedPlant
     */
    identifier?: PlantIdentifier;
    /**
     * 
     * @type {PlantInformation}
     * @memberof PatchedPlant
     */
    info?: PlantInformation;
    /**
     * 
     * @type {Date}
     * @memberof PatchedPlant
     */
    readonly datetime_added?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedPlant
     */
    description?: string;
}

/**
 * Check if a given object implements the PatchedPlant interface.
 */
export function instanceOfPatchedPlant(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedPlantFromJSON(json: any): PatchedPlant {
    return PatchedPlantFromJSONTyped(json, false);
}

export function PatchedPlantFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedPlant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'identifier': !exists(json, 'identifier') ? undefined : PlantIdentifierFromJSON(json['identifier']),
        'info': !exists(json, 'info') ? undefined : PlantInformationFromJSON(json['info']),
        'datetime_added': !exists(json, 'datetime_added') ? undefined : (new Date(json['datetime_added'])),
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function PatchedPlantToJSON(value?: PatchedPlant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identifier': PlantIdentifierToJSON(value.identifier),
        'info': PlantInformationToJSON(value.info),
        'description': value.description,
    };
}

