/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlantIdentifier
 */
export interface PlantIdentifier {
    /**
     * 
     * @type {number}
     * @memberof PlantIdentifier
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof PlantIdentifier
     */
    readonly plant: number;
    /**
     * 
     * @type {string}
     * @memberof PlantIdentifier
     */
    latin_name: string;
    /**
     * 
     * @type {string}
     * @memberof PlantIdentifier
     */
    common_name: string;
}

/**
 * Check if a given object implements the PlantIdentifier interface.
 */
export function instanceOfPlantIdentifier(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "plant" in value;
    isInstance = isInstance && "latin_name" in value;
    isInstance = isInstance && "common_name" in value;

    return isInstance;
}

export function PlantIdentifierFromJSON(json: any): PlantIdentifier {
    return PlantIdentifierFromJSONTyped(json, false);
}

export function PlantIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlantIdentifier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'plant': json['plant'],
        'latin_name': json['latin_name'],
        'common_name': json['common_name'],
    };
}

export function PlantIdentifierToJSON(value?: PlantIdentifier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'latin_name': value.latin_name,
        'common_name': value.common_name,
    };
}

